### ISSUE TITLE
How can I apply a skin?

### ISSUE THREAD

**Issue by Shadowspear123** [Wandmalfarbe/Simple-Clock-Screensaver#3]
Hey there, this screen saver is absolutely beautiful.

Just one question, for someone without any coding experience, how would I apply the skins in the source code so that I can change the default clock? I've already installed the screensaver and locate the skins in the source code.

Thanks!

**Comment by Wandmalfarbe** [comment]
That process is kind of complicated. You need to checkout the GitHub repo and compile the Xcode project yourself. Before compiling you can uncomment or comment the skin of your choice like the `BraunBN0032Dark` here: https://github.com/Wandmalfarbe/Simple-Clock-Screensaver/blob/master/SimpleClock/SimpleClock/SimpleClock.swift#L31

If you want to have `SwissRailwayClockLight` just uncomment [line 28](https://github.com/Wandmalfarbe/Simple-Clock-Screensaver/blob/master/SimpleClock/SimpleClock/SimpleClock.swift#L28) (remove the `//`) and [comment the `BraunBN0032Dark`](https://github.com/Wandmalfarbe/Simple-Clock-Screensaver/blob/master/SimpleClock/SimpleClock/SimpleClock.swift#L31) (add the `//`).
